name = "feedback-gitops-dev"
main = "src/worker/index.ts"
compatibility_date = "2026-01-01"

[assets]
binding = "ASSETS"
directory = "./public"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "feedback_gitops_audio"
bucket_name = "feedback-gitops-audio"

[[queues.producers]]
queue = "feedback-queue"
binding = "FEEDBACK_QUEUE"

[[queues.consumers]]
queue = "feedback-queue"
max_batch_size = 10
max_batch_timeout = 30

[triggers]
crons = ["*/5 * * * *"]
